### PR TITLE
ignore file not found when remove file

### LINKED ISSUE #4: FileNotFoundError when used across ray workers
I have a function which I run across multiple processes using the [ray](https://github.com/ray-project/ray) framework. This function temporarily allocates a huge portion of memory. To prevent memory errors due to too many of these allocations occurring at the same time, I want to use _ilock_.

The structure of my code is the following:

```python
@ray.remote
def _do_work(in):
    res1 = run_long_computations1(in)
    with ilock.ILock('huge allocation'):
        res2 = huge_allocation(res1)
        res3 = run_fast_computation(res2)
        del res2
    return run_long_computations2(res3)
```

Most of the time it works perfectly, but occasionally, a `FileNotFoundError` occurs which roots in _ilock_:

```
  File "~/test.py", line 7, in _do_work
    del res2
  File "~/.anaconda3/envs/myenv/lib/python3.7/site-packages/ilock/__init__.py", line 59, in __exit__
    os.unlink(self._filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ilock-9b91444836a91e7d27f6ca3479d5f0b728c7861f6622709ae0b4e2a38734655b.lock
```

Why is that? How to fix it?

### PR DESCRIPTION
**Pull request by Cologler**
fixes #4

### CODE REVIEW

**Comment by tkratky** [comment]
Hello, Who is capable to merge this Pull Request, please? Are there any requirements before the merge? 🙂

**Comment by hkcomori** [comment]
What is the reason why this pull request was closed without merging?
I want this change, because [posix-ipc](http://semanchuk.com/philip/posix_ipc/) does not support Windows (without Cygwin).

**Comment by Cologler** [comment]
@hkcomori Whatever the PR is merge or not, the package (ilock) still had a huge bug on Linux:

| process 1 | process 2 | process 3 |
|:-|:-|:-|
|own the lock: {sha256}.ilock (inode is 1)|||
||open {sha256}.ilock (inode is 1)||
|unlock and delete {sha256}.ilock|||
|||open  {sha256}.ilock (inode is 2)|
||lock {sha256}.ilock|lock {sha256}.ilock|

now both process 2 and process 3 got the lock at the same time.

**Comment by hkcomori** [comment]
Oh, I see.
We should not unlink the lock file on Linux.
However, in that case, the lock file remains even after all the processes are completed...

**Comment by Cologler** [comment]
@hkcomori If you want to remove the lock file on Linux, there is a solution at StackOverflow (https://stackoverflow.com/questions/17708885/flock-removing-locked-file-without-race-condition). 

I don't care about the lock file, so I am using https://github.com/benediktschmitt/py-filelock now.

**Comment by hkcomori** [comment]
Thanks, py-filelock solved my problem.

**Pull request closed without merging**
